version: '3'
 
services:
  sneezy-db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: "111111"
      MYSQL_USER: sneezy
      MYSQL_PASSWORD: password
    container_name: sneezy-db
    volumes:
      - sneezydb:/var/lib/mysql
    restart: always

  sneezy:
    depends_on:
      - sneezy-db
        # last known good: 45 48
    image: sneezymud/sneezymud:48
    container_name: sneezy
    cap_add:
      - SYS_PTRACE
    ports:
        - "7900:7900"
    restart: always
    volumes:
      - sneezy-lib:/home/sneezy/lib/

  buildertools:
    container_name: sneezy-buildertools
    image: sneezymud/sneezymud-buildertools:44
    ports:
        - "5001:5000"
    depends_on:
        - sneezy-db
    restart: always

  webclient:
    container_name: sneezy-webclient
    image: sneezymud/webclient:43
    ports:
        - "8080:80"
    depends_on:
        - sneezy-db
    restart: always

  websockify:
    container_name: sneezy-websockify
    image: efrecon/websockify
    command:
      - "7901"
      - "sneezy:7900"
    ports:
      - "7901:7901"
    depends_on:
        - sneezy-db
    restart: always

volumes:
  sneezydb:
  sneezy-lib:
